name: Simple Startup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
    
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo $(git log -1 --pretty=%B)
        echo Hello there!
        
