name: Simple Startup

on:
  push:
    branches: [main]
  schedule:
    - cron: '* * * * *'
    
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
        echo Hello there!
